### ISSUE TITLE
Testing Question

### ISSUE THREAD

**Issue by Wolfe-Coin** [Pankajtanwarbanna/Polymath#1]
Hey there,

Im currently testing your software and was wondering how to create an account to test the question asking / answering mechanisms.

Thanks

**Comment by Pankajtanwarbanna** [comment]
Clone repo. 
Step 1 - npm install 
Step 2 - nodemon server.js (make sure mongo database status is active )
Step 3 - Open browser localhost:8080
Step 4 - Click on Join us - Do register.
*It wont send the activation link as you have to update your own sendgrid account api key in app/models/api.js

Hope that helps.
